First assignment
========================================================

Since I have only joined this course on the last day of submission, I only had time to start this assignment. :(

First I read the activity.csv file:

```{r echo = TRUE}
data = read.csv("activity.csv")
```

I plot the histogram and calculate mean and median:

```{r echo = TRUE}
dataFactor <- as.factor(data$date)
stepsPerDay <- by(data$steps,dataFactor,sum, na.rm = F)

histogram = hist(stepsPerDay, breaks = 100, col="lightblue", xlab = "Number of steps taken a day", main = "Histogram of number of steps per day")

meanValue = mean(stepsPerDay, na.rm = T)
meanValue
medianValue = median(stepsPerDay, na.rm = T)
medianValue
```

Replacing missing data with averages:

```{r echo = TRUE}
numOfNAs <- sum(is.na(data$steps))
dataWithourNAs <- data
averagePerDay <- by(data$steps,dataFactor,mean, na.rm = F)

for(i in 1:nrow(data)){
    if(is.na(data$steps[i])){
        ind <- floor(i/208)+1
        dataWithourNAs$steps[i] <- averagePerDay[ind]
    }
}
```

I plot the histogram and calculate mean and median:

```{r echo = TRUE}
dataFactor2 <- as.factor(dataWithourNAs$date)
stepsPerDay2 <- by(dataWithourNAs$steps,dataFactor2,sum, na.rm = F)

histogram = hist(stepsPerDay2, breaks = 100, col="lightblue", xlab = "Number of steps taken a day", main = "Histogram of number of steps per day")

meanValue2 = mean(stepsPerDay2, na.rm = T)
meanValue2
medianValue2 = median(stepsPerDay2, na.rm = T)
medianValue2
```

